#!/bin/sh

for AUDIOPROC in TDA7439 TDA7313 TDA7318
do
	for DISPLAY in KS0108 KS0066
	do
		make AUDIOPROC=${AUDIOPROC} DISPLAY=${DISPLAY}
		make AUDIOPROC=${AUDIOPROC} DISPLAY=${DISPLAY} clean
	done
done
