#ifndef EEPROM_H
#define EEPROM_H

#include <inttypes.h>
#include "audio/audio.h"

/* Audio parameters values */
#define EEPROM_VOLUME				0x00

/* Alarm */
#define EEPROM_ALARM_HOUR			0x10
#define EEPROM_ALARM_MIN			0x11
#define EEPROM_ALARM_MON			0x12

/* FM tuner parameters valus */
#define EEPROM_FM_TUNER				0x20
#define EEPROM_FM_STEP				0x21
#define EEPROM_FM_MONO				0x22
#define EEPROM_FM_CTRL				0x23
#define EEPROM_FM_FREQ				0x24

/* Audio processor values */
#define EEPROM_AUDIOPROC			0x28
#define EEPROM_INPUT				0x29
#define EEPROM_LOUDNESS				0x2A

/* Display parameters */
#define EEPROM_SP_MODE				0x30
#define EEPROM_DISPLAY				0x31
#define EEPROM_BR_STBY				0x32
#define EEPROM_BR_WORK				0x33
#define EEPROM_FALL_SPEED			0x34

/* Other parameters */
#define EEPROM_ENC_RES				0x38
#define EEPROM_RC5_ADDR				0x39
#define EEPROM_TEMP_TH				0x3A
#define EEPROM_ADC_CORR_L			0x3B
#define EEPROM_ADC_CORR_R			0x3C
#define EEPROM_EXT_FUNC				0x3D
#define EEPROM_SILENCE_TIMER		0x3E

/* RC5 commands array */
#define EEPROM_RC5_CMD				0x40

/* FM stations */
#define EEPROM_STATIONS				0x70
#define EEPROM_FAV_STATIONS			0xD8

/* Text labels (maximum 15 byte followed by \0) */
#define EEPROM_LABELS_ADDR			0xF0

#define EEPROM_SIZE					0x400

/* EEPROM saved labels */
enum {
	LABEL_MUTE = MODE_SND_END,
	LABEL_LOUDNESS,
	LABEL_ON,
	LABEL_OFF,
	LABEL_DB,

	LABEL_SUNDAY,
	LABEL_MONDAY,
	LABEL_TUESDAY,
	LABEL_WEDNESDAY,
	LABEL_THURSDAY,
	LABEL_FRIDAY,
	LABEL_SADURDAY,

	LABEL_BR_WORK,

	LABEL_IN_STATUS,
	LABEL_REMOTE,
	LABEL_BUTTONS,
	LABEL_LEARN_MODE,
	LABEL_BUTTON,
	LABEL_ADDRESS,
	LABEL_COMMAND,

	LABEL_RC5_STBY,
	LABEL_RC5_MUTE,
	LABEL_RC5_MENU,
	LABEL_RC5_VOL_UP,
	LABEL_RC5_VOL_DOWN,
	LABEL_RC5_INPUT_0,
	LABEL_RC5_INPUT_1,
	LABEL_RC5_INPUT_2,
	LABEL_RC5_INPUT_3,
	LABEL_RC5_NEXT_INPUT,
	LABEL_RC5_TIME,
	LABEL_RC5_BACKLIGHT,
	LABEL_RC5_SP_MODE,
	LABEL_RC5_FALLSPEED,
	LABEL_RC5_DISPLAY,
	LABEL_RC5_TIMER,
	LABEL_RC5_ALARM,

	LABEL_RC5_CHAN_UP,
	LABEL_RC5_CHAN_DOWN,
	LABEL_RC5_FM_TUNE,
	LABEL_RC5_FM_MONO,
	LABEL_RC5_FM_STORE,
	LABEL_RC5_1,
	LABEL_RC5_2,
	LABEL_RC5_3,
	LABEL_RC5_4,
	LABEL_RC5_5,
	LABEL_RC5_6,
	LABEL_RC5_7,
	LABEL_RC5_8,
	LABEL_RC5_9,
	LABEL_RC5_0,

	LABEL_LEFT_CHANNEL,
	LABEL_RIGHT_CHANNEL,

	LABEL_THRESHOLD,
	LABEL_SENSOR,

	LABEL_END
};

#endif /* EEPROM_H */
